### ISSUE TITLE
can't compile on rhel6/python 2.6.6

### ISSUE THREAD

**Issue by dvarrazzo** [dvarrazzo/py-setproctitle#22]
Originally submitted by **ytl@slac.stanford.edu** as **issue 22**:

<b>What steps will reproduce the problem?</b>
1. download setproctitle-1.1.6
2. try to install on a rhel6 machine (python 2.6.6)

<b>What is the expected output? What do you see instead?</b>

[setproctitle-1.1.6]$ sudo python  setup.py install
running install
running build
running build_ext
building 'setproctitle' extension
creating build
creating build/temp.linux-x86_64-2.6
creating build/temp.linux-x86_64-2.6/src
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DHAVE_SYS_PRCTL_H=1 -DSPT_VERSION=1.1.6 -I/usr/include/python2.6 -c src/setproctitle.c -o build/temp.linux-x86_64-2.6/src/setproctitle.o
In file included from /usr/include/python2.6/Python.h:38,
                 from src/spt_python.h:14,
                 from src/spt.h:15,
                 from src/setproctitle.c:14:
/usr/include/string.h:548: error: expected declaration specifiers or '...' before '__locale_t'
/usr/include/string.h:549: error: nonnull argument with out-of-range operand number (argument 1, operand 3)
/usr/include/string.h:552: error: expected declaration specifiers or '...' before '__locale_t'
/usr/include/string.h:553: error: nonnull argument with out-of-range operand number (argument 1, operand 4)
error: command 'gcc' failed with exit status 1

<b>What version of the product are you using? On what operating system?</b>
- Linux BLAH 2.6.32-220.17.1.el6.x86_64 #1 SMP Thu Apr 26 13:37:13 EDT 2012 x86_64 x86_64 x86_64 GNU/Linux
- Python 2.6.6 (r266:84292, May  1 2012, 13:52:17) 
- gcc version 4.4.4 [TWW](GCC) 

<b>Please provide any additional information below.</b>
